spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriber_db
    username: user
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true